[workspace]
authors = [
  "Bia Villas Boas <villasboas@mines.edu>",
  "Guilherme Castelão <guilherme@castelao.net>",
  "Luiz Irber <luiz.irber@gmail.com>",
]
channels = ["conda-forge"]
description = "Template for a standard Python Package"
name = "pypackage-template"
platforms = ["osx-arm64", "linux-64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
copier = ">=9.7.1,<10"
pre-commit = ">=4.5.0,<5"
